spring.application.name=jobtracker

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries in Console
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true